[package]
name = "grokpad"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[features]
no-entrypoint = []
idl-build = []
test = []
