[programs.localnet]
grokpad = "24rtdj9var5RBGafZqMpm9sJKJH957XXptXctQbHwnCR"

[provider]
cluster = "localnet"
wallet = "/Users/bash/.config/solana/id.json"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.31.1"
